#### **Exercise 1:**

Last week, we started looking at the Titanic data.  Load that data again. For features that you think are of minimal importance and / or have too many NAs to make imputation feasible, drop those features.  For those that seem important, use a `SimpleImputer` to impute the data.

In [49]:
import pandas as pd
from sklearn.impute import SimpleImputer
titanic = pd.read_csv('data/titanic.csv')
titanic = titanic.drop('cabin', axis = 1)
titanic_clean = titanic[~titanic['embarked'].isna()]
titanic_clean



pclass                                             name     sex  \
0          1                    Allen, Miss. Elisabeth Walton  female   
1          1                   Allison, Master. Hudson Trevor    male   
2          1                     Allison, Miss. Helen Loraine  female   
3          1             Allison, Mr. Hudson Joshua Creighton    male   
4          1  Allison, Mrs. Hudson J C (Bessie Waldo Daniels)  female   
...      ...                                              ...     ...   
1304       3                             Zabour, Miss. Hileni  female   
1305       3                            Zabour, Miss. Thamine  female   
1306       3                        Zakarian, Mr. Mapriededer    male   
1307       3                              Zakarian, Mr. Ortin    male   
1308       3                               Zimmerman, Mr. Leo    male   

          age  sibsp  parch  ticket      fare embarked  survived  
0     29.0000      0      0   24160  211.3375        S         1  
1      0.9167      1      2  113781  151.5500        S         1  
2      2.0000      1      2  113781  151.5500        S         0  
3     30.0000      1      2  113781  151.5500        S         0  
4     25.0000      1      2  113781  151.5500        S         0  
...       ...    ...    ...     ...       ...      ...       ...  
1304  14.5000      1      0    2665   14.4542        C         0  
1305      NaN      1      0    2665   14.4542        C         0  
1306  26.5000      0      0    2656    7.2250        C         0  
1307  27.0000      0      0    2670    7.2250        C         0  
1308  29.0000      0      0  315082    7.8750        S         0  

[1307 rows x 10 columns]

In [50]:
imputer = SimpleImputer(strategy='median')
x = imputer.fit_transform(titanic[['age']])
x

array([[29.    ],
       [ 0.9167],
       [ 2.    ],
       ...,
       [26.5   ],
       [27.    ],
       [29.    ]])

In [51]:
titanic['age'] = x[:,0]
titanic

pclass                                             name     sex  \
0          1                    Allen, Miss. Elisabeth Walton  female   
1          1                   Allison, Master. Hudson Trevor    male   
2          1                     Allison, Miss. Helen Loraine  female   
3          1             Allison, Mr. Hudson Joshua Creighton    male   
4          1  Allison, Mrs. Hudson J C (Bessie Waldo Daniels)  female   
...      ...                                              ...     ...   
1304       3                             Zabour, Miss. Hileni  female   
1305       3                            Zabour, Miss. Thamine  female   
1306       3                        Zakarian, Mr. Mapriededer    male   
1307       3                              Zakarian, Mr. Ortin    male   
1308       3                               Zimmerman, Mr. Leo    male   

          age  sibsp  parch  ticket      fare embarked  survived  
0     29.0000      0      0   24160  211.3375        S         1  
1      0.9167      1      2  113781  151.5500        S         1  
2      2.0000      1      2  113781  151.5500        S         0  
3     30.0000      1      2  113781  151.5500        S         0  
4     25.0000      1      2  113781  151.5500        S         0  
...       ...    ...    ...     ...       ...      ...       ...  
1304  14.5000      1      0    2665   14.4542        C         0  
1305  28.0000      1      0    2665   14.4542        C         0  
1306  26.5000      0      0    2656    7.2250        C         0  
1307  27.0000      0      0    2670    7.2250        C         0  
1308  29.0000      0      0  315082    7.8750        S         0  

[1309 rows x 10 columns]

In [52]:
imputer = SimpleImputer(strategy='most_frequent')
x = imputer.fit_transform(titanic[['embarked']])
x[:,0]

array(['S', 'S', 'S', ..., 'C', 'C', 'S'], dtype=object)

In [53]:
titanic['embarked'] = x[:,0]
titanic.isna().sum()

pclass      0
name        0
sex         0
age         0
sibsp       0
parch       0
ticket      0
fare        1
embarked    0
survived    0
dtype: int64

#### **Exercise 2**

Sklearn does not handle strings.  Use an encoder to transform any string columns into numbers. If there are any categorical columns where label encoding won't work, use a one-hot encoder.

In [60]:
titanic_clean = titanic[['age', 'sex', 'embarked', 'survived', 'pclass']]

In [61]:
from sklearn.preprocessing import OneHotEncoder

encoder = OneHotEncoder(drop = "first", sparse_output = False)
encoder_data = encoder.fit_transform(titanic_clean[['sex', 'embarked']])
encoder_data

array([[0., 0., 1.],
       [1., 0., 1.],
       [0., 0., 1.],
       ...,
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 1.]])

In [64]:
titanic_clean[encoder.get_feature_names_out()]=encoder_data



/tmp/ipykernel_3351/2941100846.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  titanic_clean[encoder.get_feature_names_out()]=encoder_data


age     sex embarked  survived  pclass  sex_male  embarked_Q  \
0     29.0000  female        S         1       1       0.0         0.0   
1      0.9167    male        S         1       1       1.0         0.0   
2      2.0000  female        S         0       1       0.0         0.0   
3     30.0000    male        S         0       1       1.0         0.0   
4     25.0000  female        S         0       1       0.0         0.0   
...       ...     ...      ...       ...     ...       ...         ...   
1304  14.5000  female        C         0       3       0.0         0.0   
1305  28.0000  female        C         0       3       0.0         0.0   
1306  26.5000    male        C         0       3       1.0         0.0   
1307  27.0000    male        C         0       3       1.0         0.0   
1308  29.0000    male        S         0       3       1.0         0.0   

      embarked_S  
0            1.0  
1            1.0  
2            1.0  
3            1.0  
4            1.0  
...          ...  
1304         0.0  
1305         0.0  
1306         0.0  
1307         0.0  
1308         1.0  

[1309 rows x 8 columns]

In [72]:
#titanic_clean = titanic_clean.drop('sex', axis=1)
titanic_clean = titanic_clean.drop('embarked', axis=1)

titanic_clean

age  survived  pclass  sex_male  embarked_Q  embarked_S
0     29.0000         1       1       0.0         0.0         1.0
1      0.9167         1       1       1.0         0.0         1.0
2      2.0000         0       1       0.0         0.0         1.0
3     30.0000         0       1       1.0         0.0         1.0
4     25.0000         0       1       0.0         0.0         1.0
...       ...       ...     ...       ...         ...         ...
1304  14.5000         0       3       0.0         0.0         0.0
1305  28.0000         0       3       0.0         0.0         0.0
1306  26.5000         0       3       1.0         0.0         0.0
1307  27.0000         0       3       1.0         0.0         0.0
1308  29.0000         0       3       1.0         0.0         1.0

[1309 rows x 6 columns]

#### **Exercise 3**

Using 5-fold cross-validation, examine the performance of a LogisticRegression classifier. 

In [73]:
from sklearn.model_selection import cross_val_score
from sklearn.linear_model import LogisticRegression
import numpy as np

lr = LogisticRegression()

x = titanic_clean.drop("survived", axis = 1)
y = titanic_clean["survived"]

result = cross_val_score(lr, x, y , cv=5)
result

array([0.52290076, 0.82824427, 0.80916031, 0.73282443, 0.67816092])

In [74]:
np.mean(result)

np.float64(0.7142581381065193)

#### **Exercise 4**

Replace the logistic regression classifier with a decision tree classifier.  Which works better?  Why do you think that is?

In [75]:
from sklearn.tree import DecisionTreeClassifier

lr = DecisionTreeClassifier()

x = titanic_clean.drop("survived", axis = 1)
y = titanic_clean["survived"]

result = cross_val_score(lr, x, y , cv=5)
result

array([0.5       , 0.74045802, 0.66793893, 0.69465649, 0.65517241])

#### **Exercise 5:** 

See if you can get the decision tree classifier to perform better by adjusting your imputation procedure to use a KNNImputer.

#### **Exercise 6:**

Try using a `GridSearchCV` to optimize the DecisionTree algorithm.  What is the best performance you can achieve?